version: '3.8'

services:

  devops-app:
    container_name: devops-app
    build: .
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/"
          }'
    depends_on:
      - mysqldb
    ports:
      - "8791:8791"
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=tpachato
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
